name: 🚀 Deploy backend

on:
  workflow_run:
    workflows:
      - 'Backend CI'
    branches:
      - main 
    types: [completed]
  workflow_dispatch:

jobs:
  docker-amd64:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    concurrency:
      group: build_push_docker_backend_amd64
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push amd64
        uses: docker/build-push-action@v6
        with:
          context: backend
          file: backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/flathub-infra/backend:${{ github.sha }}-amd64
            ghcr.io/flathub-infra/backend:amd64-latest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
          build-args: |
            SENTRY_RELEASE=${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-arm64:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    concurrency:
      group: build_push_docker_backend_arm64
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push arm64
        uses: docker/build-push-action@v6
        with:
          context: backend
          file: backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/flathub-infra/backend:${{ github.sha }}-arm64
            ghcr.io/flathub-infra/backend:arm64-latest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
          build-args: |
            SENTRY_RELEASE=${{ github.sha }}
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create-manifest:
    needs: [docker-amd64, docker-arm64]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create ghcr.io/flathub-infra/backend:${{ github.sha }} \
            ghcr.io/flathub-infra/backend:${{ github.sha }}-amd64 \
            ghcr.io/flathub-infra/backend:${{ github.sha }}-arm64
          docker manifest create ghcr.io/flathub-infra/backend:latest \
            ghcr.io/flathub-infra/backend:amd64-latest \
            ghcr.io/flathub-infra/backend:arm64-latest
          docker manifest push ghcr.io/flathub-infra/backend:${{ github.sha }}
          docker manifest push ghcr.io/flathub-infra/backend:latest
