name: Build and deploy nginx image

on:
  push:
    branches: main
    paths:
      - "nginx/**"
      - ".github/workflows/nginx_deploy.yml"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    concurrency:
      group: build_push_docker_nginx
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: nginx
          file: nginx/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/flathub-infra/nginx:${{ github.sha }}
            ghcr.io/flathub-infra/nginx:latest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
          build-args: |
            SENTRY_RELEASE=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
